# ---- Build stage ----
FROM node:20.15.1-alpine3.19 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
RUN npm run build -- --configuration production

# ---- Serve stage ----
FROM nginx:1.27.2-alpine3.19
RUN apk --no-cache upgrade
COPY --from=builder /app/dist/tsp-map /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]