version: '3.8'
services:
  backend:
    build: ./backend
    container_name: tsp-backend
    ports:
      - '8000:8000'
    restart: always
    
  frontend:
    build: ./frontend
    container_name: tsp-frontend
    ports:
      - '8080:80'
    depends_on:
    - backend
    restart: always