# ---- Build stage ----
FROM node:22-alpine AS builder

WORKDIR /app

# Copiar arquivos de dependência
COPY package*.json ./

# Instalar dependências
RUN npm ci

# Copiar restante do código
COPY . .

# Executar build como root (evita erro de permissão no ng)
RUN npm run build -- --configuration=development --output-path=dist/tech-challenge


# ---- Serve stage ----
FROM nginx:1.27.2-alpine AS runtime

WORKDIR /usr/share/nginx/html

# Copiar artefatos com permissões corretas
COPY --from=builder --chown=nginx:nginx /app/dist/tech-challenge ./

# Substituir configuração do Nginx
COPY --chown=nginx:nginx nginx.conf /etc/nginx/conf.d/default.conf

# Rodar Nginx como usuário não-root
USER nginx

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget --spider -q http://localhost:80 || exit 1

CMD ["nginx", "-g", "daemon off;"]